### ISSUE TITLE
Unable to show proper hierarical data when tree is expanded.

### ISSUE THREAD

**Issue by AKGupta31** [dzmitry-antonenka/SwiftListTreeDataSource#1]
var dataSource = ListTreeDataSource<String>()
dataSource.append(["Ashish","Abhilesh","Ashwani"])
dataSource.append(["Anjali"], to: "Ashish")
dataSource.append(["Buggu"],to: "Anjali") 
dataSource.expandAll()        
dataSource.reload()
printDataSourceRecursively(parent: nil, level: 0)

// Print Method

func printDataSourceRecursively(parent:TreeItem<String>?,level:Int) {
        if parent == nil {
            for item in dataSource.items {
                print("Root is ", item.value)
                printDataSourceRecursively(parent: item, level: level+1)
            }
        } else {
            var extra = ""
            for _ in 0..<level {
                extra += "  "
            }
            for item in parent!.subitems {
                if let parent {
                    print(extra,"child is ", item.value)
                    if item.subitems.isEmpty == false {
                        printDataSourceRecursively(parent: item, level: level+1)
                    }
                }
            }
        }
    }

Output is:

Root is  Ashish
   child is  Anjali
     child is  Buggu
Root is  Anjali
   child is  Buggu
Root is  Buggu
Root is  Abhilesh
Root is  Ashwani

Expected Output:

Root is  Ashish
   child is  Anjali
     child is  Buggu
Root is  Buggu
Root is  Abhilesh
Root is  Ashwani

**Comment by dzmitry-antonenka** [comment]
Hello @AKGupta31 , please note to use `.backingStore` for original tree store since `.items` already flattened (include nested children) for display purposes. 

To fix your sample: `printDataSourceRecursively` needs to use `.backingStore` (might want @testable import SwiftListTreeDataSource for internal access)
More examples with built-in debugging: https://github.com/dzmitry-antonenka/SwiftListTreeDataSource#debugging

**Comment by AKGupta31** [comment]
Thank you @dzmitry-antonenka ...It worked...And thanks too for such fast reply
