### ISSUE TITLE
SwiftUI Example

### ISSUE THREAD

**Issue by cmsj** [dzmitry-antonenka/SwiftListTreeDataSource#5]
Would it be possible to get a SwiftUI example added to the repo?

**Comment by dzmitry-antonenka** [comment]
Hello @cmsj , I've added Example in TreeView app in 
https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/commit/108c43db76cffaedee858f844cd35c8c2b9cd42b

Please feel free experiment and post followup questions, thanks!

**Comment by dzmitry-antonenka** [comment]
This commit has more changes due to outdates project file fixes (Pods + SwiftPM config), for key changes please see:
- [SwiftListTreeDataStore](https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/commit/108c43db76cffaedee858f844cd35c8c2b9cd42b#diff-b6ef57b6b0d979b199aaf02674af65e976247adb5626c05d293e02d5138c1110)
- [SwiftUIListWithSearch](https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/commit/108c43db76cffaedee858f844cd35c8c2b9cd42b#diff-a25555741ebb38f04dc3c39bc4917258190c4d24c9cdba04f62bba30fa1e4a41)

**Comment by cmsj** [comment]
Nice, thanks!

**Comment by dzmitry-antonenka** [comment]
Discussion: the data source can be modified to use @published and @observableobject modifiers for properties but it will add root dependency to specific framework: SwiftUI + Combine. But it was planned to be platform agnostic...

For this reason it was moved to separate store class that mirrors needed APIs and republishes into needed properties. 

Let's see if we can improve it, I'm open for other ideas.

**Comment by dzmitry-antonenka** [comment]
Technically we can use #canImport(SwiftUI) conditions and use wrappers for in-place operations at core data source classes, but let's see if this is used feature. For now I'd keep root classes simple

**Comment by observableobject** [comment]
It would be great to support SwiftUI!

**Comment by dzmitry-antonenka** [comment]
> It would be great to support SwiftUI!

The SwiftUI is supported, please try example for your use-case. My idea to keep root classes simple and independent from any UI framework / platform specific cases. It can rewritten in C++ even and be used cross-platform, since it's plain DFS traversal

I'm personally in favor of having separate [SwiftUIViewModel](https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/commit/108c43db76cffaedee858f844cd35c8c2b9cd42b#diff-b6ef57b6b0d979b199aaf02674af65e976247adb5626c05d293e02d5138c1110) that can be tuned for whatever needs you might have.

Other option for built-in SwiftUI support would be adding default properties observation wrappers. But internal code becomes more complicated and less maintainable taking more responsibilities than needed. I'm not sure even if it will compile correctly in all cases
```
#if canImport(SwiftUI)
class DataSource: ObservableObject {
#else
class DataSource {
#endif
...
#if canImport(SwiftUI)
@Published var items: [TreeItemType] = []
#else
var items: [TreeItemType] = []
#endif
```
